### ISSUE TITLE
We need a better name for this project

### ISSUE THREAD

**Issue by olymk2** [maidstone-hackspace/dockyard#2]
We cant really use docker in the name, so ideas ?

**Comment by MightySCollins** [comment]
And a better Icon xD

**Comment by mannion007** [comment]
Whale Tank? Container Ship?.. lol

**Comment by olymk2** [comment]
Jonah, ie Jonah and the whale :)

**Comment by olymk2** [comment]
or latin for whale Cetacea

**Comment by olymk2** [comment]
vessel (kind of container and ship at the same time)

**Comment by olymk2** [comment]
or whaler :-D

**Comment by olymk2** [comment]
feeder (type of conatiner ship)

**Comment by olymk2** [comment]
beluga

**Comment by MightySCollins** [comment]
Narwhal

**Comment by apepindev** [comment]
Dockyard/Shipyard? Could go more convoluted and pick a name from a historic shipyard from [wikipedia](https://en.wikipedia.org/wiki/Shipyard)?

**Comment by MightySCollins** [comment]
+1 for Dockyard

**Comment by olymk2** [comment]
Dcokyard sounds good to me :)
