### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by MightySCollins** [maidstone-hackspace/dockyard#9]
I think we should be licensing our work, I like both [MIT](https://opensource.org/licenses/MIT) and [WTFPL (Do What the Fuck You Want to Public License)](http://www.wtfpl.net/).

There are more choices at [choosealicense.com](http://choosealicense.com/), what do you think?

**Comment by olymk2** [comment]
I automatically license stuff as GPL 3, which most open source software uses so i tend to go in that direction.

not sure about the WTFPL license as thats not well known

**Comment by MightySCollins** [comment]
GLP 3 is fine with me, WTFPL is mainly just a bit of fun.
